onlyBuiltDependencies:
  - esbuild
  - '@vercel/speed-insights'

overrides:
  # Security override: Force all dependencies to use cookie@>=0.7.0 due to vulnerabilities in earlier versions.
  # See CVE-2022-25912: https://nvd.nist.gov/vuln/detail/CVE-2022-25912
  cookie@<0.7.0: '>=0.7.0'
